package com.sprint.msdp.commandservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-02-19T13:07:51.261-05:00
 * Generated source version: 2.7.15
 * 
 */
@WebService(targetNamespace = "http://sprint.com/msdp/commandservice", name = "EsbCommandService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EsbCommandService {

    @WebResult(name = "commandResponse", targetNamespace = "http://sprint.com/msdp/commandservice", partName = "parameters")
    @WebMethod
    public CommandResponse commandRequest(
        @WebParam(partName = "parameters", name = "commandRequest", targetNamespace = "http://sprint.com/msdp/commandservice")
        CommandRequest parameters
    ) throws WSExceptionException;
}
