
package com.drutt.ws.msdp.media.search.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IndexerSearchApi", targetNamespace = "http://ws.drutt.com/msdp/media/search/v2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IndexerSearchApi {


    /**
     * 
     * @param searchAssetsRequest
     * @return
     *     returns com.drutt.ws.msdp.media.search.v2.SearchAssetsResponse
     * @throws WSException_Exception
     */
    @WebMethod
    @WebResult(name = "searchAssetsResponse", targetNamespace = "http://ws.drutt.com/msdp/media/search/v2", partName = "searchAssetsResponse")
    public SearchAssetsResponse searchAssets(
        @WebParam(name = "searchAssetsRequest", targetNamespace = "http://ws.drutt.com/msdp/media/search/v2", partName = "searchAssetsRequest")
        SearchAssetsRequest searchAssetsRequest)
        throws WSException_Exception
    ;

    /**
     * 
     * @param getAssetsByTicketIdRequest
     * @return
     *     returns com.drutt.ws.msdp.media.search.v2.GetAssetsByTicketIdResponse
     * @throws WSException_Exception
     */
    @WebMethod
    @WebResult(name = "getAssetsByTicketIdResponse", targetNamespace = "http://ws.drutt.com/msdp/media/search/v2", partName = "getAssetsByTicketIdResponse")
    public GetAssetsByTicketIdResponse getAssetsByTicketId(
        @WebParam(name = "getAssetsByTicketIdRequest", targetNamespace = "http://ws.drutt.com/msdp/media/search/v2", partName = "getAssetsByTicketIdRequest")
        GetAssetsByTicketIdRequest getAssetsByTicketIdRequest)
        throws WSException_Exception
    ;

}
